version: '3'
services:
     nginx:
          depends_on:
               - prep
          image: 'nginx:1.17.3'
          container_name: 'nginx'
          volumes:
               - ./nginx/nginx.conf:/etc/nginx/nginx.conf
               - ./nginx/access_lists/:/etc/nginx/access_lists/
               - ./nginx/log/:/var/log/nginx/
          ports:
               - 9000:9000
               - 7100:7100
          external_links:
               - prep
          restart: always

     prep:
          image: 'iconloop/prep-node:1909111919x74b59c'
          container_name: 'prep'
          environment:
               LOOPCHAIN_LOG_LEVEL: "DEBUG"
               ICON_LOG_LEVEL: "DEBUG"
               DEFAULT_PATH: "/data/loopchain"
               LOG_OUTPUT_TYPE: "file"
               CERT_PATH: "/cert"
               TZ: "Europe/Vienna"
               PRIVATE_PATH: "/cert/keystore"
               PRIVATE_PASSWORD: "<KEYSTORE PASSWORD>"
          cap_add:
               - SYS_TIME
          volumes:
               - ./data:/data
               - ./cert:/cert
          expose:
               - '9000'
               - '7100'
          restart: always
