version: '3'
services:
   nginx:
      image: 'nginx:1.17.3'
      container_name: 'nginx'
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/whitelist.conf:/etc/nginx/whitelist.conf
      ports:
         - 80:80
         - 7100:7100
      restart: always
   
   citizen-node:
      depends_on:
         - nginx
      image: 'iconloop/citizen-node:1908271151xd2b7a4'
      container_name: 'citizen-node'
      environment:
         LOOPCHAIN_LOG_LEVEL: 'DEBUG'
         LOG_OUTPUT_TYPE: 'file'
         #FASTEST_START: 'yes' # Restore from lastest snapshot DB
      volumes:
         - ./data:/data  # mount a data volumes
         - ./keys:/citizen_pack/keys  # Automatically generate cert key files here
      ports:
         - 10001:9000
         - 10002:7100
      restart: always
